{% set name = "emmet-builders" %}
{% set version = "0.38.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emmet-builders-{{ version }}.tar.gz
  sha256: 253b73361ba795c935589ac288b21d54375c8d0ace157778ef38235b60c1a9d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - emmet-core
    - maggma >=0.47.3
    - matminer >=0.7.3
    - python >=3.8

test:
  imports:
    - emmet.builders
    - emmet.builders.feff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/emmet
  summary: Builders for the Emmet Library
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
