{% set name = "emmet-builders" %}
{% set version = "0.85.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 876524f4b622d02ddbbc7b04fc9eb8404354f965128795d9c7db14dc6bb056ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
    - pip
  run:
    - pymatgen-io-validation >=0.1.1
    - mdanalysis >=2.7.0
    - solvation_analysis >=0.4.0
    - python >={{ python_min }}
    - emmet-core >=0.85
    - maggma >=0.57.6
    - matminer >=0.9.1

test:
  imports:
    - emmet.builders
    - emmet.builders.abinit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/materialsproject/emmet
  summary: Builders for the Emmet Library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
