{% set name = "emmet-builders" %}
{% set version = "0.75.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emmet-builders-{{ version }}.tar.gz
  sha256: a1e2bd1c67dbb46344c89d3bd4bd83f6a3544f5753b1d43963f081df862518a2
  patches:
    - setup.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - emmet-core
    - maggma >=0.57.6
    - matminer >=0.7.3

test:
  imports:
    - emmet.builders
    - emmet.builders.abinit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/emmet
  summary: Builders for the Emmet Library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
