{% set name = "emmet-builders" %}
{% set version = "0.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/materialsproject/emmet/archive/v{{ version }}.tar.gz
  sha256: 96faa008b25fbb7777fd28cdf0703b8b2af8153a1b7b7099e76f67e09c88a5a9

build:
  noarch: python
  script: cd emmet-builders && {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - emmet-core
    - maggma >=0.47.3
    - matminer >=0.7.3
    - python >=3.8

test:
  imports:
    - emmet.builders
    - emmet.builders.feff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/emmet
  summary: Builders for the Emmet Library
  license: BSD-3-Clause & MIT & Apache-2.0 & BSD-2-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
