{% set name = "emmet-builders" %}
{% set version = "0.54.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emmet-builders-{{ version }}.tar.gz
  sha256: 745468aff551582901ed62253cfaddc9abf2218bf8bad1d15a0a581a22953c1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - emmet-core
    - maggma >=0.49.17
    - matminer >=0.7.3,<0.8
    - python >=3.8

test:
  imports:
    - emmet.builders
    - emmet.builders.feff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/emmet
  summary: Builders for the Emmet Library
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
