{% set name = "emmet-builders" %}
{% set version = "0.70.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emmet-builders-{{ version }}.tar.gz
  sha256: 43a820bf285531a85ee3500da0593b408ffaaa2f56dc37df3c56070d4546c6cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - emmet-core
    - maggma >=0.57.0
    - matminer >=0.7.3,<0.8

test:
  imports:
    - emmet.builders
    - emmet.builders.abinit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/emmet
  summary: Builders for the Emmet Library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
