{% set name = "emmet-builders" %}
{% set version = "0.84.10" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 12cfffe995546f1b45d1f9fa6bd82c408876864389e8d9a6ad59b28114bfb799

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
    - pip
  run:
    - pymatgen-io-validation >=0.1.0
    - mdanalysis >=2.7.0
    - solvation_analysis >=0.4.0
    - python >={{ python_min }}
    - emmet-core
    - maggma >=0.57.6
    - matminer >=0.9.1

test:
  imports:
    - emmet.builders
    - emmet.builders.abinit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/materialsproject/emmet
  summary: Builders for the Emmet Library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
